<?php
declare(strict_types=1);
require_once __DIR__ . '/core/database.php'; require_once __DIR__ . '/event-lib.php';
$filter = in_array($_GET['filter'] ?? 'all', ['all', 'upcoming', 'past'], true) ? (string)$_GET['filter'] : 'all';
$where = "status='published'";
if ($filter === 'upcoming') $where .= ' AND event_date >= CURDATE()';
if ($filter === 'past') $where .= ' AND event_date < CURDATE()';
$events=$pdo->query("SELECT * FROM events WHERE {$where} ORDER BY event_date " . ($filter === 'past' ? 'DESC' : 'ASC'))->fetchAll(); $pageTitle='رویدادهای مکسا'; require __DIR__ . '/dashboard/components/header/component.php';
?>
<style>
.events-page{background:#f4f7f6;padding:52px 20px 80px;direction:rtl}.events-wrap{max-width:1180px;margin:auto}.events-kicker{color:#007b7a;font-weight:800;font-size:13px;margin-bottom:10px}.events-page h1{font-size:clamp(30px,4vw,56px);color:#123a3d;margin:0 0 14px}.events-lead{max-width:640px;color:#607277;line-height:2;margin-bottom:24px}.events-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:28px}.event-filters{display:flex;gap:8px;flex-wrap:wrap}.event-filters a{border:1px solid #d6e3e2;border-radius:9px;padding:8px 13px;color:#537074;font-size:12px;font-weight:800;background:#fff}.event-filters a.active{background:#007b7a;border-color:#007b7a;color:#fff}.events-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.public-event-card{background:#fff;border:1px solid #e3eceb;border-radius:18px;overflow:hidden;box-shadow:0 12px 34px rgba(21,66,68,.08)}.public-event-card .cover{height:190px;background:linear-gradient(135deg,#006e70,#0ca2a3 55%,#f5a623);position:relative}.public-event-card .cover img{width:100%;height:100%;object-fit:cover}.public-event-card .cover span{position:absolute;right:16px;bottom:14px;background:rgba(255,255,255,.88);color:#075f61;border-radius:8px;padding:5px 9px;font-size:11px;font-weight:800}.public-event-card .body{padding:18px}.public-event-card h2{font-size:18px;color:#173d40;line-height:1.7;margin:0 0 8px}.public-event-card p{color:#64777a;font-size:13px;line-height:1.9;min-height:50px}.public-event-card .date{color:#007b7a;font-size:12px;font-weight:800}.public-event-card a{display:inline-flex;margin-top:16px;color:#007b7a;font-weight:800;font-size:13px}.event-empty{grid-column:1/-1;text-align:center;padding:54px 20px;background:#fff;border:1px dashed #cddddd;border-radius:16px;color:#728285}.event-empty strong{display:block;color:#173d40;font-size:18px;margin-bottom:6px}@media(max-width:900px){.events-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.events-grid{grid-template-columns:1fr}.events-page{padding-inline:16px}.events-toolbar{align-items:stretch}.event-filters a{flex:1;text-align:center}}
</style>
<main class="events-page"><div class="events-wrap"><div class="events-kicker">تقویم مکسا</div><h1>رویدادها و همایش‌ها</h1><p class="events-lead">همایش‌ها، نشست‌ها و برنامه‌های آموزشی مکسا را دنبال کنید و جزئیات هر رویداد را در صفحه اختصاصی آن ببینید.</p><div class="events-toolbar"><div class="event-filters" aria-label="فیلتر رویدادها"><a class="<?= $filter==='all'?'active':'' ?>" href="/events.php?filter=all">همه رویدادها</a><a class="<?= $filter==='upcoming'?'active':'' ?>" href="/events.php?filter=upcoming">پیش‌رو</a><a class="<?= $filter==='past'?'active':'' ?>" href="/events.php?filter=past">برگزارشده</a></div><span class="muted"><?= event_h((string)count($events)) ?> رویداد</span></div><div class="events-grid"><?php if(!$events): ?><div class="event-empty"><strong>رویدادی در این دسته پیدا نشد</strong><span>به‌زودی برنامه‌های جدید مکسا در این بخش قرار می‌گیرد.</span></div><?php else: foreach($events as $event): ?><article class="public-event-card"><div class="cover"><?php if($event['poster']): ?><img src="<?= event_h($event['poster']) ?>" alt="پوستر <?= event_h($event['title']) ?>"><?php endif; ?><span><?= event_h(event_date_label($event['event_date'])) ?></span></div><div class="body"><h2><?= event_h($event['title']) ?></h2><p><?= event_h($event['short_description']) ?></p><div class="date">شروع رویداد: <?= event_h(substr((string)$event['start_time'],0,5)) ?></div><a href="/event.php?slug=<?= rawurlencode($event['slug']) ?>">مشاهده صفحه رویداد ←</a></div></article><?php endforeach; endif; ?></div></div></main>
<?php require __DIR__ . '/dashboard/components/footer/component.php';
