<?php
declare(strict_types=1);
require_once __DIR__ . '/_guard.php'; dash_require('events'); dash_require_hq();
require_once __DIR__ . '/../event-lib.php';
$pdo = dash_pdo(); $id = (int)($_GET['id'] ?? 0);
$event = ['id'=>0,'title'=>'','slug'=>'','event_date'=>'','start_time'=>'08:00:00','short_description'=>'','about'=>'','poster'=>null,'schedule_pdf'=>null,'registration_url'=>'','status'=>'draft','banner_active'=>0,'banner_label'=>'رویداد پیش‌رو','banner_cta'=>'مشاهده رویداد','banner_link'=>'','banner_theme'=>'teal','banner_dismissible'=>1,'banner_background'=>'#007b7a','banner_text_color'=>'#ffffff','banner_accent_color'=>'#f4a61e'];
$heroes = $people = $speakers = $partners = [];
if ($id) { $st=$pdo->prepare('SELECT * FROM events WHERE id=?'); $st->execute([$id]); $event=array_merge($event,$st->fetch() ?: []); $q=function(string $sql)use($pdo,$id){$s=$pdo->prepare($sql);$s->execute([$id]);return $s->fetchAll();}; $heroes=$q('SELECT * FROM event_heroes WHERE event_id=? ORDER BY sort_order,id'); $people=$q('SELECT * FROM event_people WHERE event_id=? ORDER BY sort_order,id'); $speakers=$q('SELECT * FROM event_speakers WHERE event_id=? ORDER BY sort_order,id'); $partners=$q('SELECT * FROM event_partners WHERE event_id=? ORDER BY sort_order,id'); }
[$jy,$jm,$jd] = $event['event_date'] ? event_gregorian_to_jalali((int)substr($event['event_date'],0,4),(int)substr($event['event_date'],5,2),(int)substr($event['event_date'],8,2)) : [1405,7,16];
$jalaliDate = sprintf('%04d/%02d/%02d',$jy,$jm,$jd); $PANEL_TITLE = $id ? 'ویرایش رویداد' : 'ساخت رویداد'; require __DIR__ . '/_panel_head.php';
function rowValue(array $row,string $key): string { return event_h((string)($row[$key] ?? '')); }
?>
<style>
.event-form{max-width:1100px;margin:0 auto}.section-title{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.section-title h2{margin:0}.repeat-list{display:grid;gap:10px}.repeat-row{display:grid;grid-template-columns:1.1fr 1.1fr 1fr auto;gap:10px;align-items:end;padding:12px;border:1px solid var(--color-border);border-radius:13px;background:var(--color-bg)}.repeat-row input,.repeat-row select,.event-form textarea,.event-form input[type=text],.event-form input[type=time],.event-form input[type=url],.event-form select{width:100%;border:1px solid var(--color-border);background:var(--color-bg);border-radius:11px;padding:10px 12px;font:inherit;color:var(--color-text)}.event-form textarea{min-height:135px;resize:vertical}.repeat-row label,.event-form label{font-size:12px;font-weight:700;display:grid;gap:6px}.file-note{font-size:11px;color:var(--color-muted)}.cover-preview{max-width:180px;max-height:110px;object-fit:cover;border-radius:10px}.form-split{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}.check-line{display:flex;align-items:center;gap:9px;padding:12px 0;font-weight:700;font-size:13px}.check-line input{accent-color:var(--color-primary);width:18px;height:18px}.actions{justify-content:flex-start}.banner-preview-label{font-size:11px;color:var(--color-muted);font-weight:800;margin:14px 0 7px}.banner-preview{position:relative;display:flex;align-items:center;justify-content:center;gap:9px;flex-wrap:wrap;min-height:54px;padding:9px 40px 9px 12px;border-radius:12px;background:#007b7a;color:#fff;font-size:11px;text-align:center;overflow:hidden}.banner-preview.amber{background:#e89a16}.banner-preview.dark{background:#123a3d}.banner-preview strong{font-size:12px}.banner-preview button[data-preview=cta]{border:1px solid rgba(255,255,255,.65);border-radius:7px;background:transparent;color:inherit;padding:5px 9px;font:inherit;font-weight:800}.banner-preview .preview-close{position:absolute;right:10px;top:50%;transform:translateY(-50%);border:0;background:transparent;color:inherit;font-size:20px;line-height:1;cursor:pointer}@media(max-width:760px){.form-split{grid-template-columns:1fr}.repeat-row{grid-template-columns:1fr 1fr}.repeat-row .remove-row{grid-column:1/-1}.actions .btn{width:auto}}
</style>
<style>
.smart-select-grid{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:8px;margin-top:6px}.smart-select-grid select{height:46px}.smart-time-grid{grid-template-columns:1fr 1fr}.smart-control-label{font-size:12px;font-weight:800;color:var(--color-text)}
.file-drop-label{display:grid!important;gap:8px}.file-drop{display:flex;align-items:center;justify-content:center;min-height:92px;padding:14px;border:1.5px dashed #a9c9c7;border-radius:14px;background:linear-gradient(145deg,rgba(0,123,122,.06),rgba(244,166,30,.05));color:var(--color-primary-dark);font-size:12px;font-weight:800;text-align:center;cursor:pointer;transition:border-color .2s,background .2s,transform .2s}.file-drop:hover,.file-drop.is-dragging{border-color:var(--color-primary);background:rgba(0,123,122,.12);transform:translateY(-1px)}.file-drop.has-file{border-style:solid;border-color:var(--success);background:rgba(22,163,122,.08);color:var(--success)}.file-drop-input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}.file-drop small{display:block;color:var(--color-muted);font-weight:500;margin-top:4px}.color-control-grid{display:grid;gap:10px;margin-top:14px}.color-control{display:grid;grid-template-columns:34px 1fr;gap:9px;align-items:center}.color-control input[type=color]{width:34px;height:34px;padding:0;border:0;border-radius:9px;background:none;cursor:pointer}.color-control input[type=text]{height:40px!important;font-family:monospace!important;direction:ltr;text-align:left}.banner-preview.custom{background:#007b7a;color:#fff}.banner-preview.custom .preview-accent{color:#f4a61e}.banner-preview.custom button[data-preview=cta]{border-color:#f4a61e}
@media(max-width:640px){.smart-select-grid{grid-template-columns:1fr}.smart-time-grid{grid-template-columns:1fr 1fr}.file-drop{min-height:78px}}
</style>
<form class="event-form" action="event-save.php" method="post" enctype="multipart/form-data" data-banner-bg="<?= event_h($event['banner_background']) ?>" data-banner-text="<?= event_h($event['banner_text_color']) ?>" data-banner-accent="<?= event_h($event['banner_accent_color']) ?>">
<?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$event['id'] ?>"><input type="hidden" name="slug" value="<?= event_h($event['slug']) ?>">
<div class="page-head"><div class="ph-ic">◫</div><div><h1><?= $id?'ویرایش رویداد':'ساخت رویداد جدید' ?></h1><p>اطلاعات پایه، محتوای صفحه و بنر سراسری رویداد</p></div></div>
<section class="card"><div class="section-title"><div><h2>اطلاعات پایه</h2><p class="hint">این بخش عنوان و تاریخ اصلی صفحه را کنترل می‌کند.</p></div></div><div class="grid2"><div class="field"><label>نام رویداد<input type="text" name="title" required value="<?= event_h($event['title']) ?>"></label></div><div class="field"><label>تاریخ برگزاری شمسی<input type="text" name="jalali_date" required dir="ltr" placeholder="۱۴۰۵/۰۷/۱۶" value="<?= event_h($jalaliDate) ?>"></label></div><div class="field"><label>ساعت شروع<input type="time" name="start_time" value="<?= event_h(substr((string)$event['start_time'],0,5)) ?>" dir="ltr"></label></div><div class="field"><label>وضعیت<select name="status"><option value="draft" <?= $event['status']==='draft'?'selected':'' ?>>پیش‌نویس</option><option value="published" <?= $event['status']==='published'?'selected':'' ?>>منتشرشده</option><option value="archived" <?= $event['status']==='archived'?'selected':'' ?>>آرشیو</option></select></label></div></div><div class="field"><label>توضیحات کوتاه<input type="text" name="short_description" value="<?= event_h($event['short_description']) ?>"></label></div><div class="field"><label>درباره رویداد<textarea name="about"><?= event_h($event['about']) ?></textarea></label></div></section>
<section class="card"><div class="section-title"><div><h2>رسانه و ثبت‌نام</h2><p class="hint">فایل‌ها بعداً هم از همین فرم قابل جایگزینی هستند.</p></div></div><div class="grid2"><div class="field"><label>پوستر رویداد<input type="file" name="poster" accept="image/*"><?php if($event['poster']): ?><img class="cover-preview" src="<?= event_h($event['poster']) ?>" alt="پوستر فعلی"><?php endif; ?></label></div><div class="field"><label>فایل سین همایش<input type="file" name="schedule_pdf" accept="application/pdf"><span class="file-note"><?= $event['schedule_pdf']?'فایل فعلی ثبت شده است.':'' ?></span></label></div></div><div class="field"><label>لینک ثبت‌نام<input type="url" name="registration_url" dir="ltr" placeholder="https://" value="<?= event_h($event['registration_url']) ?>"></label></div></section>
<section class="card"><div class="section-title"><div><h2>هیروهای اختصاصی</h2><p class="hint">فقط در صفحه همین رویداد نمایش داده می‌شوند.</p></div><button type="button" class="tbtn" data-add="hero">＋ افزودن هیرو</button></div><div class="repeat-list" id="hero-list"><?php foreach($heroes as $r): ?><div class="repeat-row"><label>عنوان<input name="hero_title[]" value="<?= rowValue($r,'title') ?>"></label><label>توضیح<input name="hero_description[]" value="<?= rowValue($r,'description') ?>"></label><label>متن دکمه<input name="hero_button_label[]" value="<?= rowValue($r,'button_label') ?>"></label><label>لینک<input name="hero_link[]" dir="ltr" value="<?= rowValue($r,'button_link') ?>"></label><label>تصویر<input type="file" name="hero_image[]" accept="image/*"><input type="hidden" name="hero_existing[]" value="<?= rowValue($r,'image') ?>"></label><button type="button" class="tbtn danger remove-row">حذف</button></div><?php endforeach; ?></div></section>
<section class="card"><div class="section-title"><div><h2>دبیران همایش</h2><p class="hint">دبیر علمی و اجرایی، همراه با عکس و سمت.</p></div><button type="button" class="tbtn" data-add="person">＋ افزودن دبیر</button></div><div class="repeat-list" id="person-list"><?php foreach($people as $r): ?><div class="repeat-row"><label>نوع<select name="person_role[]"><option value="scientific_secretary" <?= $r['role']==='scientific_secretary'?'selected':'' ?>>دبیر علمی</option><option value="executive_secretary" <?= $r['role']==='executive_secretary'?'selected':'' ?>>دبیر اجرایی</option></select></label><label>نام<input name="person_name[]" value="<?= rowValue($r,'name') ?>"></label><label>سمت<input name="person_title[]" value="<?= rowValue($r,'title') ?>"></label><label>عکس<input type="file" name="person_image[]" accept="image/*"><input type="hidden" name="person_existing[]" value="<?= rowValue($r,'image') ?>"></label><button type="button" class="tbtn danger remove-row">حذف</button></div><?php endforeach; ?></div></section>
<section class="card"><div class="section-title"><div><h2>اساتید حاضر</h2><p class="hint">لیست تصویری اساتید و سخنرانان رویداد.</p></div><button type="button" class="tbtn" data-add="speaker">＋ افزودن استاد</button></div><div class="repeat-list" id="speaker-list"><?php foreach($speakers as $r): ?><div class="repeat-row"><label>نام<input name="speaker_name[]" value="<?= rowValue($r,'name') ?>"></label><label>سمت / تخصص<input name="speaker_title[]" value="<?= rowValue($r,'title') ?>"></label><label>ترتیب<input name="speaker_order[]" type="text" dir="ltr" value="<?= rowValue($r,'sort_order') ?>"></label><label>عکس<input type="file" name="speaker_image[]" accept="image/*"><input type="hidden" name="speaker_existing[]" value="<?= rowValue($r,'image') ?>"></label><button type="button" class="tbtn danger remove-row">حذف</button></div><?php endforeach; ?></div></section>
<section class="card"><div class="section-title"><div><h2>همراهان همایش</h2><p class="hint">نام و لوگوی سازمان‌ها و شرکت‌های همراه.</p></div><button type="button" class="tbtn" data-add="partner">＋ افزودن همراه</button></div><div class="repeat-list" id="partner-list"><?php foreach($partners as $r): ?><div class="repeat-row"><label>نام شرکت<input name="partner_name[]" value="<?= rowValue($r,'name') ?>"></label><label>ترتیب<input name="partner_order[]" type="text" dir="ltr" value="<?= rowValue($r,'sort_order') ?>"></label><label>لوگو<input type="file" name="partner_logo[]" accept="image/*"><input type="hidden" name="partner_existing[]" value="<?= rowValue($r,'logo') ?>"></label><span></span><button type="button" class="tbtn danger remove-row">حذف</button></div><?php endforeach; ?></div></section>
<section class="card banner-settings"><div class="section-title"><div><h2>بنر بالای سایت</h2><p class="hint">فقط یک رویداد می‌تواند هم‌زمان بنر فعال داشته باشد. پیش‌نمایش با اطلاعات همین فرم به‌روزرسانی می‌شود.</p></div></div><label class="check-line"><input type="checkbox" name="banner_active" value="1" <?= (int)$event['banner_active']?'checked':'' ?>> نمایش بنر این رویداد در بالای سایت</label><div class="form-split"><div class="field"><label>متن کوچک بنر<input data-banner-preview="label" type="text" name="banner_label" value="<?= event_h($event['banner_label']) ?>"></label><label>متن دکمه<input data-banner-preview="cta" type="text" name="banner_cta" value="<?= event_h($event['banner_cta']) ?>"></label><label>لینک بنر<input type="url" name="banner_link" dir="ltr" value="<?= event_h($event['banner_link']) ?>"></label><label class="check-line"><input type="checkbox" name="banner_dismissible" value="1" <?= (int)$event['banner_dismissible']?'checked':'' ?>> امکان بستن موقت بنر برای کاربران</label></div><div class="field"><label>تم رنگی<select data-banner-preview="theme" name="banner_theme"><option value="teal" <?= $event['banner_theme']==='teal'?'selected':'' ?>>فیروزه‌ای مکسا</option><option value="amber" <?= $event['banner_theme']==='amber'?'selected':'' ?>>کهربایی</option><option value="dark" <?= $event['banner_theme']==='dark'?'selected':'' ?>>تیره</option></select></label><div class="banner-preview-label">پیش‌نمایش زنده</div><div id="bannerPreview" class="banner-preview"><span data-preview="label"><?= event_h($event['banner_label']) ?></span><strong><?= event_h($event['title'] ?: 'عنوان رویداد') ?></strong><span>۱۲ روز · ۰۸ ساعت · ۲۴ دقیقه</span><button type="button" data-preview="cta"><?= event_h($event['banner_cta']) ?></button><button type="button" class="preview-close" aria-label="بستن موقت">×</button></div></div></div></section>
<?php if($event['id']): ?><section class="card"><div class="section-title"><div><h2>اخبار اختصاصی رویداد</h2><p class="hint">این خبرها فقط در صفحه همین رویداد نمایش داده می‌شوند و از اخبار اصلی سایت جدا هستند.</p></div><a class="tbtn" href="event-news-list.php?event_id=<?= (int)$event['id'] ?>">مدیریت اخبار این رویداد</a></div></section><?php else: ?><section class="card"><div class="section-title"><div><h2>اخبار اختصاصی رویداد</h2><p class="hint">بعد از ذخیره اولین نسخه رویداد، می‌توانید خبرهای اختصاصی آن را اضافه و مدیریت کنید.</p></div></div></section><?php endif; ?>
<div class="actions"><button class="btn btn-primary" type="submit">ذخیره رویداد</button><a class="btn btn-ghost" href="event-list.php">انصراف</a></div>
</form>
<script>
(function(){
  const templates={hero:'<div class="repeat-row"><label>عنوان<input name="hero_title[]"></label><label>توضیح<input name="hero_description[]"></label><label>متن دکمه<input name="hero_button_label[]"></label><label>لینک<input name="hero_link[]" dir="ltr"></label><label>تصویر<input type="file" name="hero_image[]" accept="image/*"><input type="hidden" name="hero_existing[]"></label><button type="button" class="tbtn danger remove-row">حذف</button></div>',person:'<div class="repeat-row"><label>نوع<select name="person_role[]"><option value="scientific_secretary">دبیر علمی</option><option value="executive_secretary">دبیر اجرایی</option></select></label><label>نام<input name="person_name[]"></label><label>سمت<input name="person_title[]"></label><label>عکس<input type="file" name="person_image[]" accept="image/*"><input type="hidden" name="person_existing[]"></label><button type="button" class="tbtn danger remove-row">حذف</button></div>',speaker:'<div class="repeat-row"><label>نام<input name="speaker_name[]"></label><label>سمت / تخصص<input name="speaker_title[]"></label><label>ترتیب<input name="speaker_order[]" type="text" dir="ltr" value="0"></label><label>عکس<input type="file" name="speaker_image[]" accept="image/*"><input type="hidden" name="speaker_existing[]"></label><button type="button" class="tbtn danger remove-row">حذف</button></div>',partner:'<div class="repeat-row"><label>نام شرکت<input name="partner_name[]"></label><label>ترتیب<input name="partner_order[]" type="text" dir="ltr" value="0"></label><label>لوگو<input type="file" name="partner_logo[]" accept="image/*"><input type="hidden" name="partner_existing[]"></label><span></span><button type="button" class="tbtn danger remove-row">حذف</button></div>'};
  document.addEventListener('click',function(e){const add=e.target.closest('[data-add]');if(add){document.getElementById(add.dataset.add+'-list').insertAdjacentHTML('beforeend',templates[add.dataset.add]);}if(e.target.closest('.remove-row'))e.target.closest('.repeat-row').remove();});
  const preview=document.getElementById('bannerPreview');
  if(preview){
    const sync=()=>{const label=document.querySelector('[data-banner-preview="label"]');const cta=document.querySelector('[data-banner-preview="cta"]');const theme=document.querySelector('[data-banner-preview="theme"]');if(label)preview.querySelector('[data-preview="label"]').textContent=label.value||'رویداد پیش‌رو';if(cta)preview.querySelector('[data-preview="cta"]').textContent=cta.value||'مشاهده رویداد';if(theme)preview.className='banner-preview '+theme.value;};
    document.querySelectorAll('[data-banner-preview]').forEach(el=>el.addEventListener('input',sync));sync();
  }
})();
</script>
<script>
(function(){
  const form=document.querySelector('.event-form'); if(!form)return;
  const faDigits=value=>String(value).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
  const fileText=input=>{const accept=input.accept||'';return accept.includes('pdf')?'PDF تا ۲۵ مگابایت':'تصویر JPG، PNG یا WEBP تا ۱۲ مگابایت';};
  const mountDrop=input=>{
    if(input.dataset.dropReady==='1')return; input.dataset.dropReady='1';
    const label=input.closest('label'); if(!label)return; label.classList.add('file-drop-label'); input.classList.add('file-drop-input');
    const box=document.createElement('span'); box.className='file-drop'; box.innerHTML='<span>فایل را اینجا رها کنید یا برای انتخاب کلیک کنید<small>'+fileText(input)+'</small></span>'; label.insertBefore(box,input);
    const update=()=>{const file=input.files&&input.files[0];box.classList.toggle('has-file',!!file);box.querySelector('span').firstChild.textContent=file?('انتخاب شد: '+file.name):'فایل را اینجا رها کنید یا برای انتخاب کلیک کنید';};
    input.addEventListener('change',update); box.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();input.click()});
    ['dragenter','dragover'].forEach(name=>box.addEventListener(name,e=>{e.preventDefault();box.classList.add('is-dragging')}));
    ['dragleave','drop'].forEach(name=>box.addEventListener(name,e=>{e.preventDefault();box.classList.remove('is-dragging')}));
    box.addEventListener('drop',e=>{if(e.dataTransfer.files&&e.dataTransfer.files.length){try{input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change',{bubbles:true}))}catch(err){}}}); update();
  };
  const scan=()=>document.querySelectorAll('.event-form input[type=file]').forEach(mountDrop); scan(); new MutationObserver(scan).observe(form,{childList:true,subtree:true});

  const makeSelect=(name,items,value)=>{const s=document.createElement('select');s.name=name;s.className='smart-select';items.forEach(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;if(String(v)===String(value))o.selected=true;s.appendChild(o)});return s;};
  const dateInput=form.querySelector('input[name=jalali_date]');
  if(dateInput){
    const parts=(dateInput.value||'1405/07/16').split('/').map(Number),wrap=document.createElement('span');wrap.className='smart-select-grid';
    const years=[];for(let y=1400;y<=1410;y++)years.push([y,faDigits(y)]);const months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'].map((x,i)=>[i+1,x]);const days=[];for(let d=1;d<=31;d++)days.push([d,faDigits(d)]);
    const ys=makeSelect('jalali_year',years,parts[0]),ms=makeSelect('jalali_month',months,parts[1]),ds=makeSelect('jalali_day',days,parts[2]);wrap.append(ys,ms,ds);dateInput.type='hidden';dateInput.closest('label').appendChild(wrap);const sync=()=>dateInput.value=[ys.value,String(ms.value).padStart(2,'0'),String(ds.value).padStart(2,'0')].join('/');[ys,ms,ds].forEach(s=>s.addEventListener('change',sync));sync();
  }
  const timeInput=form.querySelector('input[name=start_time]');
  if(timeInput){const parts=(timeInput.value||'08:00').split(':').map(Number),wrap=document.createElement('span');wrap.className='smart-select-grid smart-time-grid';const hs=[],mins=[];for(let h=0;h<24;h++)hs.push([String(h).padStart(2,'0'),faDigits(String(h).padStart(2,'0'))]);for(let m=0;m<60;m+=5)mins.push([String(m).padStart(2,'0'),faDigits(String(m).padStart(2,'0'))]);const h=makeSelect('start_hour',hs,String(parts[0]).padStart(2,'0')),m=makeSelect('start_minute',mins,String(parts[1]??0).padStart(2,'0'));wrap.append(h,m);timeInput.type='hidden';timeInput.closest('label').appendChild(wrap);const sync=()=>timeInput.value=h.value+':'+m.value;[h,m].forEach(s=>s.addEventListener('change',sync));sync();}

  const theme=form.querySelector('[data-banner-preview="theme"]'),preview=document.getElementById('bannerPreview');
  if(preview&&!preview.querySelector('.preview-accent')){const accent=preview.querySelector('span:nth-of-type(2)');if(accent)accent.classList.add('preview-accent');}
  if(theme&&preview){const colors=[['banner_background','رنگ زمینه',form.dataset.bannerBg||'#007b7a'],['banner_text_color','رنگ متن',form.dataset.bannerText||'#ffffff'],['banner_accent_color','رنگ تأکیدی',form.dataset.bannerAccent||'#f4a61e']];const grid=document.createElement('div');grid.className='color-control-grid';colors.forEach(([name,label,value])=>{const row=document.createElement('label');row.className='color-control';row.innerHTML='<input type="color" value="'+value+'" aria-label="'+label+'"><input type="text" name="'+name+'" value="'+value+'" maxlength="7" pattern="#[0-9A-Fa-f]{6}" aria-label="'+label+' کد HEX">';const picker=row.querySelector('input[type=color]'),text=row.querySelector('input[type=text]');const sync=source=>{let v=source.value.trim();if(!/^#[0-9a-f]{6}$/i.test(v))return;picker.value=v;text.value=v;preview.style.setProperty('--banner-bg',form.querySelector('[name=banner_background]').value);preview.style.setProperty('--banner-text',form.querySelector('[name=banner_text_color]').value);preview.style.setProperty('--banner-accent',form.querySelector('[name=banner_accent_color]').value);preview.style.background=preview.style.getPropertyValue('--banner-bg');preview.style.color=preview.style.getPropertyValue('--banner-text');preview.querySelector('[data-preview="cta"]').style.borderColor=preview.style.getPropertyValue('--banner-accent');preview.querySelector('.preview-accent').style.color=preview.style.getPropertyValue('--banner-accent');};picker.addEventListener('input',()=>sync(picker));text.addEventListener('input',()=>sync(text));row.prepend(document.createElement('span'));row.firstChild.textContent='';grid.appendChild(row)});theme.closest('.field').appendChild(grid);const syncTheme=()=>{preview.className='banner-preview custom '+theme.value};theme.addEventListener('change',syncTheme);syncTheme();grid.querySelectorAll('input[type=color]').forEach(i=>i.dispatchEvent(new Event('input')));}
})();
</script>
</div></body></html>
