<?php
declare(strict_types=1);
require_once __DIR__ . '/_guard.php'; dash_require('events'); dash_require_hq();
require_once __DIR__ . '/../event-lib.php';
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { header('Location: event-list.php'); exit; }
csrf_check(); $pdo=dash_pdo(); $id=(int)($_POST['id']??0); $title=trim((string)($_POST['title']??'')); $date=event_jalali_input_to_date((string)($_POST['jalali_date']??''));
if($title===''||!$date){http_response_code(422);exit('عنوان و تاریخ شمسی معتبر الزامی است.');}
$time=preg_match('/^\d{2}:\d{2}$/',(string)($_POST['start_time']??''))?(string)$_POST['start_time'].':00':'08:00:00'; $slug=$id?(string)($_POST['slug']??''):event_slug($title); $status=in_array($_POST['status']??'draft',['draft','published','archived'],true)?$_POST['status']:'draft';
try{ $pdo->beginTransaction(); $poster=null; $pdf=null; if(!empty($_FILES['poster']['name']))$poster=event_asset($_FILES['poster'],'poster',['jpg','jpeg','png','webp'],12000000); if(!empty($_FILES['schedule_pdf']['name']))$pdf=event_asset($_FILES['schedule_pdf'],'schedule',['pdf'],25000000);
  $fields=['title'=>$title,'slug'=>$slug,'event_date'=>$date,'start_time'=>$time,'short_description'=>trim((string)($_POST['short_description']??'')),'about'=>trim((string)($_POST['about']??'')),'registration_url'=>trim((string)($_POST['registration_url']??'')),'status'=>$status,'banner_active'=>empty($_POST['banner_active'])?0:1,'banner_label'=>trim((string)($_POST['banner_label']??'رویداد پیش‌رو')),'banner_cta'=>trim((string)($_POST['banner_cta']??'مشاهده رویداد')),'banner_link'=>trim((string)($_POST['banner_link']??'')),'banner_theme'=>in_array($_POST['banner_theme']??'teal',['teal','amber','dark'],true)?$_POST['banner_theme']:'teal'];
  if($id){$set='title=:title,slug=:slug,event_date=:event_date,start_time=:start_time,short_description=:short_description,about=:about,registration_url=:registration_url,status=:status,banner_active=:banner_active,banner_label=:banner_label,banner_cta=:banner_cta,banner_link=:banner_link,banner_theme=:banner_theme';$params=$fields+['id'=>$id];if($poster){$set.=',poster=:poster';$params['poster']=$poster;}if($pdf){$set.=',schedule_pdf=:schedule_pdf';$params['schedule_pdf']=$pdf;}$st=$pdo->prepare("UPDATE events SET $set WHERE id=:id");$st->execute($params);}else{$fields['poster']=$poster;$fields['schedule_pdf']=$pdf;$fields['created_by']=(int)(dash_user()['id']??0);$cols=implode(',',array_keys($fields));$vals=':'.implode(',:',array_keys($fields));$st=$pdo->prepare("INSERT INTO events ($cols) VALUES ($vals)");$st->execute($fields);$id=(int)$pdo->lastInsertId();}
  if(!empty($fields['banner_active'])){$pdo->prepare('UPDATE events SET banner_active=0 WHERE id<>?')->execute([$id]);}
  foreach(['event_heroes','event_people','event_speakers','event_partners'] as $table)$pdo->prepare("DELETE FROM $table WHERE event_id=?")->execute([$id]);
  $saveRows=function(string $table,array $names,array $extra,string $fileKey,string $existingKey)use($pdo,$id){$n=max(count($names),count($_POST[$extra[0]]??[])); for($i=0;$i<$n;$i++){ $name=trim((string)($names[$i]??''));if($name==='')continue;$image=(string)($_POST[$existingKey][$i]??'');if(isset($_FILES[$fileKey]['name'][$i])&&$_FILES[$fileKey]['name'][$i]!==''){$f=[];foreach(['name','type','tmp_name','error','size'] as $k)$f[$k]=$_FILES[$fileKey][$k][$i]??null;$image=event_asset($f,$fileKey,['jpg','jpeg','png','webp'],8000000)??$image;}$row=['event_id'=>$id,'name'=>$name,'image'=>$image,'sort_order'=>(int)($_POST[$extra[1]][$i]??$i)];if($table==='event_people'){$row['role']=$_POST['person_role'][$i]??'scientific_secretary';$row['title']=trim((string)($_POST['person_title'][$i]??''));$st=$pdo->prepare('INSERT INTO event_people(event_id,role,name,title,image,sort_order)VALUES(?,?,?,?,?,?)');$st->execute([$id,$row['role'],$name,$row['title'],$image,$row['sort_order']]);}elseif($table==='event_speakers'){$row['title']=trim((string)($_POST['speaker_title'][$i]??''));$st=$pdo->prepare('INSERT INTO event_speakers(event_id,name,title,image,sort_order)VALUES(?,?,?,?,?)');$st->execute([$id,$name,$row['title'],$image,$row['sort_order']]);}else{$st=$pdo->prepare("INSERT INTO $table(event_id,title,description,image,button_link,sort_order)VALUES(?,?,?,?,?,?)");$st->execute([$id,$name,'',$image,'',$row['sort_order']]);}}};
  $saveRows('event_people',$_POST['person_name']??[],['person_name','person_order'],'person_image','person_existing');$saveRows('event_speakers',$_POST['speaker_name']??[],['speaker_name','speaker_order'],'speaker_image','speaker_existing');
  $pn=$_POST['partner_name']??[];for($i=0;$i<count($pn);$i++){if(trim($pn[$i])==='')continue;$logo=(string)($_POST['partner_existing'][$i]??'');if(!empty($_FILES['partner_logo']['name'][$i])){$f=[];foreach(['name','type','tmp_name','error','size'] as $k)$f[$k]=$_FILES['partner_logo'][$k][$i]??null;$logo=event_asset($f,'partner',['jpg','jpeg','png','webp'],8000000)??$logo;}$pdo->prepare('INSERT INTO event_partners(event_id,name,logo,sort_order)VALUES(?,?,?,?)')->execute([$id,trim($pn[$i]),$logo,(int)($_POST['partner_order'][$i]??$i)]);}
  $ht=$_POST['hero_title']??[];for($i=0;$i<count($ht);$i++){if(trim($ht[$i])==='')continue;$img=(string)($_POST['hero_existing'][$i]??'');if(!empty($_FILES['hero_image']['name'][$i])){$f=[];foreach(['name','type','tmp_name','error','size'] as $k)$f[$k]=$_FILES['hero_image'][$k][$i]??null;$img=event_asset($f,'hero',['jpg','jpeg','png','webp'],12000000)??$img;}$pdo->prepare('INSERT INTO event_heroes(event_id,title,description,image,button_link,sort_order)VALUES(?,?,?,?,?,?)')->execute([$id,trim($ht[$i]),trim((string)($_POST['hero_description'][$i]??'')),$img,trim((string)($_POST['hero_link'][$i]??'')),$i]);}
  $pdo->commit(); dash_audit($id?'event_updated':'event_created',['event_id'=>$id]); header('Location: event-list.php'); exit;
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();http_response_code(500);echo 'ذخیره رویداد انجام نشد: '.event_h($e->getMessage());}
